tools:
  external_code_coverage:
    timeout: 1800
    runs: 3

build:
  environment:
    php:
      version: 7.2

  nodes:
    phpcs:
      tests:
        override:
          - phpcs-run src/ tests/

    psalm:
      environment:
        php:
          ini:
            'memory_limit': -1
      dependencies:
        override:
          - pecl install apcu
          - composer require --dev vimeo/psalm:^3.4
      tests:
        override:
          - command: vendor/bin/psalm --report-show-info=false --report=checkstyle.xml
            analysis:
              file: checkstyle.xml
              format: 'general-checkstyle'

    phpstan:
      environment:
        php:
          ini:
            'memory_limit': -1
      dependencies:
        override:
          - pecl install apcu
          - pecl install redis
          - pecl install memcached
          - composer require --dev phpstan/phpstan-shim:^0.11
      tests:
        override:
          - vendor/bin/phpstan.phar analyse src/

build_failure_conditions:
  # Issues reported by any analyzer (which generates report in checkstyle format) like phpcs
  - 'issues.count > 0'
  # Code Coverage decreased from previous inspection
  - 'project.metric_change("scrutinizer.test_coverage", < -0.01)'
  # Code Coverage drops below 90%
  - 'project.metric("scrutinizer.test_coverage", < 0.90)'
