name: CakePHP CI

on:
  push:
    branches:
      - master
      - '4.next'
  pull_request:
    branches:
      - '*'

jobs:
  testsuite-windows:
    runs-on: windows-2019
    name: PHP 7.4 & mssql

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: '7.4'
        extensions: mbstring, intl, apcu, pdo_sqlsrv
        ini-values: apc.enable_cli = 1, extension = php_fileinfo.dll
        coverage: none

    - name: Setup SQLServer
      run: |
        SqlLocalDB start MSSQLLocalDB
        sqlcmd -S "(localdb)\MSSQLLocalDB" -Q "create database cakephp;"

    - name: composer install
      run: composer install

    - name: Run PHPUnit
      env:
        REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
        DB_DSN: 'sqlserver://@(localdb)\MSSQLLocalDB/cakephp'
      run: |
          vendor/bin/phpunit
