name: Coding Standard

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 10
        
    - name: Setup PHP
      run: |
        sudo apt remove php7.2-fpm
        sudo apt install php7.2-intl php7.2-mbstring
        sudo update-alternatives --set php /usr/bin/php7.2
        sudo update-alternatives --set phar /usr/bin/phar7.2
        sudo update-alternatives --set phar.phar /usr/bin/phar.phar7.2
        sudo update-alternatives --set phpize /usr/bin/phpize7.2
        sudo update-alternatives --set php-config /usr/bin/php-config7.2
        
    - name: composer install
      run: composer install
      
    - name: Run PHP CodeSniffer
      run: vendor/bin/phpcs --colors --parallel=16 -p src/ tests/
